[build]
  publish = "dist"
  command = "export ELM_HOME=\"elm-stuff\" && npm install && npm test && npm run build"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["elm-stuff"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
